name: Redmi 9C NFC NetHunter Kernel Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential cpio libncurses-dev python3 python3-pip

      - name: Download Toolchain (aarch64)
        run: |
          mkdir -p toolchains
          curl -L https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/12.2.0/aarch64-linux-gnu.tar.xz | tar -xJ -C toolchains
          export PATH=$GITHUB_WORKSPACE/toolchains/aarch64-linux-gnu/bin:$PATH

      - name: Configure Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make angelican_defconfig

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) Image.gz-dtb

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: redmi9c-kernel
          path: arch/arm64/boot/Image.gz-dtb
